@StockGuru_HostAddress = http://localhost:5007/api

######################

// Get All Stocks
GET {{StockGuru_HostAddress}}/stocks
Accept: application/json

###

// Get Stock By Id
GET {{StockGuru_HostAddress}}/stocks/id
Accept: application/json

###

// Update Stock
PUT http://{{StockGuru_HostAddress}}/stocks/id
Content-Type: application/json

{
  "symbol": "UpdatedName",
  "companyName": "Apple Inc.",
  "purchase": 150.00,
  "lastDiv": 0.82,
  "industry": "Technology",
  "marketCap": 2230000000000
}

###

// Delete Stock
DELETE http://{{StockGuru_HostAddress}}/stocks/id
Content-Type: application/json


#######################################

// Get All Comments
GET {{StockGuru_HostAddress}}/comments
Accept: application/json

###

// Get Comment By Id
GET {{StockGuru_HostAddress}}/comments/id
Accept: application/json

###

// Create Comment
POST http://{{StockGuru_HostAddress}}/comments/stockId
Content-Type: application/json

{
  "title": "string",
  "content": "string"
}

###

// Update Comment
PUT http://{{StockGuru_HostAddress}}/comments/id
Content-Type: application/json

{
  "title": "string",
  "content": "string"
}

###

// Delete Comment
DELETE http://{{StockGuru_HostAddress}}/comments/id
Content-Type: application/json

###